export const THEME_LIGHT = "THEME_LIGHT";
export const THEME_DARK = "THEME_DARK";
export const TOGGLE_THEME = "TOGGLE_THEME";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const TOGGLE_SIDEBAR_MENU = "TOGGLE_SIDEBAR_MENU";
